<?php

const THEME_STUDIO_CONFIG = '/boot/config/plugins/theme.studio/theme.json';
const THEME_STUDIO_PERSISTENT_CSS = '/boot/config/plugins/theme.studio/theme.css';
const THEME_STUDIO_LIVE_CSS = '/usr/local/emhttp/plugins/theme.studio/sheets/ThemeStudioButton.css';

function theme_studio_defaults(): array
{
    return [
        'name' => 'Midnight Orange',
        'background' => '#121212',
        'surface' => '#1d1b1b',
        'surfaceAlt' => '#262626',
        'text' => '#f2f2f2',
        'textMuted' => '#a8a8a8',
        'accent' => '#ff8c2f',
        'accentHover' => '#ffad66',
        'border' => '#404040',
        'headerBackground' => '#1d1b1b',
        'headerText' => '#ffffff',
        'positive' => '#33cc33',
        'warning' => '#ffd324',
        'danger' => '#e22828',
        'radius' => 8,
        'density' => 'comfortable',
    ];
}

function theme_studio_validate(array $input): array
{
    $defaults = theme_studio_defaults();
    $output = [];
    $output['name'] = trim((string)($input['name'] ?? $defaults['name']));
    $output['name'] = substr($output['name'] ?: $defaults['name'], 0, 48);

    foreach (array_keys($defaults) as $key) {
        if (!is_string($defaults[$key]) || $key === 'name' || $key === 'density') {
            continue;
        }
        $value = strtoupper(trim((string)($input[$key] ?? $defaults[$key])));
        $output[$key] = preg_match('/^#[0-9A-F]{6}$/', $value) ? $value : $defaults[$key];
    }

    $output['radius'] = max(0, min(24, (int)($input['radius'] ?? $defaults['radius'])));
    $density = (string)($input['density'] ?? $defaults['density']);
    $output['density'] = in_array($density, ['compact', 'comfortable'], true) ? $density : $defaults['density'];
    return $output;
}

function theme_studio_load(): array
{
    if (!is_file(THEME_STUDIO_CONFIG)) {
        return theme_studio_defaults();
    }
    $decoded = json_decode((string)file_get_contents(THEME_STUDIO_CONFIG), true);
    return is_array($decoded) ? theme_studio_validate($decoded) : theme_studio_defaults();
}

function theme_studio_css(array $theme): string
{
    $t = theme_studio_validate($theme);
    $gap = $t['density'] === 'compact' ? '6px' : '10px';
    $name = str_replace(['*/', "\r", "\n"], '', $t['name']);

    return <<<CSS
/* Generated by UNRAID Theme Studio: {$name}. Do not edit this file directly. */
html:root[class*="Theme--"] {
  --text-color: {$t['text']};
  --alt-text-color: {$t['textMuted']};
  --blockquote-text-color: {$t['textMuted']};
  --disabled-text-color: {$t['textMuted']};
  --inverse-text-color: {$t['background']};
  --link-text-color: {$t['accent']};
  --background-color: {$t['background']};
  --opac-background-color: {$t['background']}F2;
  --mild-background-color: {$t['surfaceAlt']};
  --alt-background-color: {$t['surface']};
  --dashboard-background-color: {$t['surface']};
  --dashboard-icon-color: {$t['surfaceAlt']};
  --dashboard-title-action-color: {$t['textMuted']};
  --usage-bar-background-color: {$t['surfaceAlt']};
  --usage-bar-used-background-color: {$t['accent']};
  --usage-disk-background-color: {$t['surfaceAlt']};
  --inverse-background-color: {$t['text']};
  --radio-background-color: {$t['surfaceAlt']};
  --disabled-input-background-color: {$t['surfaceAlt']};
  --border-color: {$t['border']};
  --alt-border-color: {$t['border']};
  --disabled-border-color: {$t['border']};
  --inverse-border-color: {$t['border']};
  --input-border-color: {$t['border']};
  --disabled-input-border-color: {$t['border']};
  --textarea-border-color: {$t['border']};
  --table-border-color: {$t['border']};
  --table-alt-border-color: {$t['border']};
  --table-background-color: {$t['surface']};
  --table-header-background-color: {$t['surfaceAlt']};
  --hover-table-row-background-color: {$t['surfaceAlt']};
  --dashboard-border-color: {$t['border']};
  --footer-text: {$t['textMuted']};
  --footer-background-color: {$t['surfaceAlt']};
  --header-text-color: {$t['headerText']};
  --header-background-color: {$t['headerBackground']};
  --title-header-background-color: {$t['surfaceAlt']};
  --hr-color: {$t['border']};
  --scrollbar-color: {$t['textMuted']};
  --scrollbar-hover-color: {$t['text']};
  --checkbox-color: {$t['surfaceAlt']};
  --checkbox-hover-color: {$t['accent']};
  --brand-orange: {$t['accent']};
  --brand-red: {$t['danger']};
  --button-text-color: {$t['accent']};
  --hover-button-text-color: {$t['background']};
  --hover-button-background: {$t['accentHover']};
  --input-bg-color: {$t['surface']};
  --focus-input-bg-color: {$t['surfaceAlt']};
  --focus-input-background-color: {$t['surfaceAlt']};
  --focus-input-border-color: {$t['accent']};
  --shade-bg-color: {$t['surfaceAlt']};
  --dynamix-ui-dropdownchecklist-color: {$t['text']};
  --dynamix-ui-dropdownchecklist-color-alt1: {$t['surface']};
  --dynamix-ui-dropdownchecklist-color-alt2: {$t['surfaceAlt']};
  --dynamix-ui-dropdownchecklist-dropcontainer-border-color: {$t['border']};
  --dynamix-ui-state-active-border-color: {$t['accent']};
  --dynamix-sb-message-bg-color: {$t['surface']};
  --dynamix-sb-message-text-color: {$t['text']};
  --dynamix-sb-message-link-color: {$t['accent']};
  --dynamix-sb-title-bg-color: {$t['surfaceAlt']};
  --dynamix-sb-title-text-color: {$t['text']};
  --dynamix-sb-wrapper-bg-color: {$t['surface']};
  --dynamix-sb-wrapper-border-color: {$t['border']};
  --dynamix-sb-wrapper-text-color: {$t['text']};
  --dynamix-sb-body-text-color: {$t['text']};
  --dynamix-sb-body-bg-color: {$t['surface']};
  --dynamix-sweet-alert-text-color: {$t['text']};
  --dynamix-sweet-alert-icon-bg-color: {$t['surface']};
  --dynamix-tablesorter-thead-row-border-color: {$t['border']};
  --dynamix-tablesorter-thead-th-text-color: {$t['text']};
  --dynamix-tablesorter-thead-th-bg-color: {$t['surfaceAlt']};
  --dynamix-tablesorter-tbody-row-bg-color: {$t['surface']};
  --dynamix-tablesorter-tbody-row-alt-bg-color: {$t['surfaceAlt']};
  --dynamix-tablesorter-tbody-row-border-color: {$t['border']};
  --dynamix-select-bg-color: {$t['surface']};
  --dynamix-select-box-shadow: 0 0 0 1px {$t['border']};
  --dynamix-select-disabled-bg-color: {$t['surfaceAlt']};
  --dynamix-select-disabled-border-color: {$t['border']};
  --dynamix-select-disabled-color: {$t['textMuted']};
  --dynamix-box-text-color: {$t['text']};
  --dynamix-box-inner-div-border-color: {$t['border']};
  --dynamix-tooltipster-sidetip-bg-from: {$t['surfaceAlt']};
  --dynamix-tooltipster-sidetip-bg-to: {$t['surface']};
  --dynamix-tooltipster-sidetip-content-text-color: {$t['text']};
  --dynamix-tooltipster-sidetip-arrow-bg-color: {$t['surface']};
  --dynamix-tooltipster-sidetip-arrow-border-color: {$t['border']};
  --dynamix-tooltipster-sidetip-box-border-color: {$t['accent']};
  --dynamix-filetree-bg-color: {$t['surface']};
  --dynamix-awesomplete-text-color: {$t['text']};
  --dynamix-awesomplete-list-bg-color: {$t['surface']};
  --dynamix-awesomplete-list-bg-from-color: {$t['surfaceAlt']};
  --dynamix-awesomplete-list-bg-to-color: {$t['surface']};
  --dynamix-awesomplete-list-border-color: {$t['border']};
  --dynamix-awesomplete-list-shadow-color: {$t['border']};
  --dynamix-awesomplete-list-before-bg-color: {$t['surface']};
  --dynamix-awesomplete-list-item-hover-bg-color: {$t['surfaceAlt']};
  --dynamix-awesomplete-list-item-hover-text-color: {$t['text']};
  --dynamix-awesomplete-list-item-selected-bg-color: {$t['accent']};
  --dynamix-awesomplete-list-item-selected-text-color: {$t['background']};
  --dynamix-awesomplete-mark-bg-color: {$t['warning']};
  --dynamix-awesomplete-mark-hover-bg-color: {$t['accentHover']};
  --dynamix-awesomplete-mark-selected-bg-color: {$t['positive']};
  --theme-studio-positive: {$t['positive']};
  --theme-studio-warning: {$t['warning']};
  --theme-studio-danger: {$t['danger']};
  --theme-studio-radius: {$t['radius']}px;
  --theme-studio-gap: {$gap};
}

body, #displaybox { background-color: var(--background-color); color: var(--text-color); }
a, .fa-external-link { color: var(--link-text-color); }
table.tablesorter { background-color: var(--dynamix-tablesorter-tbody-row-bg-color); }
.Theme--nav-top .nav-item a,
.Theme--nav-top .nav-user a { color: var(--text-color); }
.Theme--nav-top .nav-item:hover a,
.Theme--nav-top .nav-item:focus-within a { color: var(--link-text-color); }
.Theme--nav-top .nav-item:focus:after,
.Theme--nav-top .nav-item:hover:after,
.Theme--nav-top .nav-item.active:after { background-color: var(--brand-orange); }
.Theme--sidebar .nav-item a { color: var(--alt-text-color); }
.Theme--sidebar .nav-item:hover a,
.Theme--sidebar .nav-item.active a { color: var(--text-color); }
input:not([type="button"]):not([type="submit"]), select, textarea,
.ui-dialog, .sweet-alert, .context-menu-list {
  background-color: var(--input-bg-color);
  color: var(--text-color);
  border-color: var(--input-border-color);
}
.dashboard .box, .dashboard-card, .tile, .ui-dialog, .sweet-alert,
input, select, textarea, button { border-radius: var(--theme-studio-radius); }
.dashboard .box, .dashboard-card, .tile { background-color: var(--dashboard-background-color); }
.green, .status-green, .fa-check-circle { color: var(--theme-studio-positive); }
.orange, .status-orange, .fa-exclamation-triangle { color: var(--theme-studio-warning); }
.red, .status-red, .fa-times-circle { color: var(--theme-studio-danger); }
table tbody td { padding-top: var(--theme-studio-gap); padding-bottom: var(--theme-studio-gap); }
CSS;
}

function theme_studio_atomic_write(string $path, string $contents): bool
{
    $directory = dirname($path);
    if (!is_dir($directory) && !mkdir($directory, 0755, true) && !is_dir($directory)) {
        return false;
    }
    $temporary = $path . '.tmp.' . getmypid();
    if (file_put_contents($temporary, $contents, LOCK_EX) === false) {
        return false;
    }
    chmod($temporary, 0644);
    return rename($temporary, $path);
}

function theme_studio_save(array $theme): bool
{
    $validated = theme_studio_validate($theme);
    $json = json_encode($validated, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . "\n";
    $css = theme_studio_css($validated);
    return theme_studio_atomic_write(THEME_STUDIO_CONFIG, $json)
        && theme_studio_atomic_write(THEME_STUDIO_PERSISTENT_CSS, $css)
        && theme_studio_atomic_write(THEME_STUDIO_LIVE_CSS, $css);
}
